# Array Creation:

*1. Initialize an empty array with size 2X2.*

In [ ]:
import numpy as np
empty_array = np.ones((2,2))
print(empty_array)

[[1. 1.]
 [1. 1.]]


*2. Initialize an all one array with size 4X2.*

In [ ]:
ones_array = np.ones((4,2))
print("Ones Array:",ones_array)

Ones Array: [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


*3. Return a new array of given shape and type, filled with fill value*

In [ ]:
full_array = np.full((3,3),1,dtype=int)
print(full_array)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


*4. Return a new array of zeros with same shape and type as a given array.*

In [ ]:
zero_arr = np.zeros_like(full_array)
print(zero_arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


*5. Return a new array of ones with same shape and type as a given array*

In [ ]:
ones_array = np.ones_like(full_array)
print(ones_array)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


 *6. For an existing list new_list = [1,2,3,4] convert to an numpy array*

In [ ]:
new_list = [1,2,3,4]
new_array = np.array(new_list)
print(new_list)

[1, 2, 3, 4]


# Array Manipulation:

*1. Create an array with values ranging from 10 to 49.*

In [ ]:
numFrom10to49=np.arange(10,50)
print(numFrom10to49)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


*2.Create a 3X3 matrix with values ranging from 0 to 8.*

In [ ]:
matrix = np.arange(0,9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


*3. Create a 3X3 identity matrix*

In [ ]:
ident_matrix = np.eye(3,3)
print(ident_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


*4. Create a random array of size 30 and find the mean of the array.*

In [ ]:
randomArr = np.random.random(30)
print(randomArr)
print(randomArr.mean())


[0.49401811 0.87144445 0.74777667 0.11129887 0.31117    0.42116941
 0.53812114 0.99460118 0.7005678  0.33415204 0.57653165 0.25522636
 0.2650122  0.31976216 0.94507601 0.31699867 0.2041306  0.66394326
 0.17151261 0.47592032 0.11477408 0.62328628 0.11076519 0.57680136
 0.90219473 0.92970824 0.02193192 0.76270248 0.49304074 0.60691853]
0.4953519028292775


5. *Create a 10X10 array with random values and find the minimum and maximum *

In [ ]:
array10 = np.random.random((10,10))
print(array10)
print(array10.max())
print(array10.min())

[[0.40984808 0.85402069 0.99432085 0.94883301 0.98009077 0.45834791
  0.36341039 0.90463513 0.96748816 0.41801865]
 [0.36501546 0.91916779 0.13488916 0.18911122 0.27866369 0.11403867
  0.2220386  0.85976614 0.96008865 0.43446158]
 [0.54359596 0.26971331 0.78507895 0.49906775 0.67585864 0.7737624
  0.50176534 0.41669531 0.64613202 0.0940383 ]
 [0.75684588 0.16037245 0.42224733 0.84435573 0.41102447 0.98863636
  0.3044993  0.38257898 0.07235709 0.74215028]
 [0.09143269 0.54085642 0.64989781 0.94352289 0.02028515 0.06512188
  0.71859393 0.28916469 0.06757555 0.52977428]
 [0.46124013 0.93134781 0.48864013 0.13593672 0.39276826 0.54178273
  0.76665052 0.93159609 0.10422808 0.93995595]
 [0.93044034 0.59975446 0.54401545 0.20332971 0.45447087 0.77781539
  0.05163283 0.98238395 0.90457581 0.03147035]
 [0.99846392 0.93759048 0.32835528 0.01741063 0.40787643 0.2864028
  0.74565501 0.26323746 0.72215924 0.73757214]
 [0.28395551 0.17910946 0.07918706 0.05610657 0.84728487 0.27838743
  0.5631547  0

* 6. Create a zero array of size 10 and replace 5th element with 1. *

In [ ]:
zero_ar = np.zeros(10);
zero_ar[4] = 1;
print(zero_ar)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


*7. Reverse an array arr = [1,2,0,0,4,0]. *

In [ ]:
arr2 = [1,2,0,0,4,0]
reversed_arr2 = arr2[::-1]
print(reversed_arr2)

[0, 4, 0, 0, 2, 1]


8. Create a 2d array with 1 on border and 0 inside.
*italicized text*

In [ ]:
Array = np.zeros((5,5));
Array[0,:]=1;
Array[:,0] =1;
Array[4,:]=1;
Array[:,4]=1;

print(Array)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


*9. Create a 8X8 matrix and fill it with a checkerboard pattern. *

In [ ]:
matriz = np.zeros((8,8));
matriz[1::2,::2] = 1
matriz[::2,1::2]=1
print(matriz)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# Array Operations:

*1. Add the two array.*

In [ ]:
x = np.array([[1,2],[3,5]]);
y = np.array([[5,6],[7,8]]);

addition = x + y;
print(addition)

[[ 6  8]
 [10 13]]


*2. Subtract the two array. *

In [ ]:
subtraction = x - y;
print(subtraction)

[[-4 -4]
 [-4 -3]]


*3. Multiply the array with any integers of your choice. *

In [ ]:
multplication = x * y ;
print(multplication)

[[ 5 12]
 [21 40]]


*4. Find the square of each element of the array. *

In [ ]:
SquareArr1= np.square(x)
SquareArr2 =np.square(y)
print(SquareArr1)
print(SquareArr2)

[[ 1  4]
 [ 9 25]]
[[  1  16]
 [ 81 625]]


*5. Find the dot product between: v(and)w ; x(and)v ; x(and)y. *

In [ ]:
import numpy as np;
v = np.array([9,10])
w= np.array([11,12])
x = np.array([[1,2],[3,5]]);
y = np.array([[5,6],[7,8]]);
DotVW= np.dot(v,w);
Dotxy = np.dot(x,y)
Dotxv = np.dot(x,v)
print(DotVW)
print("----------")
print(Dotxy)
print("---------")
print(Dotxv)

219
----------
[[19 22]
 [50 58]]
---------
[29 77]


*6. Concatenate x(and)y along row and Concatenate v(and)w along column. *

In [ ]:
from typing import Concatenate
v = np.array([9,10])
w= np.array([11,12])
x = np.array([[1,2],[3,5]]);
y = np.array([[5,6],[7,8]]);
ConcatenateRow = np.vstack((x,y));
ConcatenateColumn = np.concatenate((v,w));
print(ConcatenateRow)
print(ConcatenateColumn)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[ 9 10 11 12]


*7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error? *

In [ ]:
x = np.array([[1,2],[3,5]]);
v = np.array([9,10])
ConacatenateXV = np.concatenate((x,v))
print(ConacatenateXV)
#

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

# Matrix Operations:

*1. Prove A.A−1 = I. *

In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]]);
INV_A = np.linalg.inv(A);
# print(INV_A)
DotAinv_a = np.dot(A,INV_A);
print(DotAinv_a)
print(np.allclose(DotAinv_a, np.eye(2)))



[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
True


*2. Prove AB ̸= BA. *

In [ ]:
DotAB = np.dot(A,B);
DotBA = np.dot(B,A);
Array_check = np.array_equal(DotAB,DotBA)
print(Array_check)

False


*3. Prove (AB)T = BTAT. *

In [ ]:
TransAB = np.transpose(DotAB)
AtranBtran = np.dot(np.transpose(B),np.transpose(A));
check_array = np.array_equal(TransAB,AtranBtran)
print(check_array)

True


• Solve the following system of Linear equation using Inverse Methods.
2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9 *italicized text*


In [ ]:
A = np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
B = np.array([-1,-3,9])
invA = np.linalg.inv(A)
x = np.dot(invA,B)
Ax = np.dot(A,x)
print(Ax)
print(B)


[-1. -3.  9.]
[-1 -3  9]


# How Fast is Numpy?

*1. Element-wise Addition:*

In [4]:
import numpy as np;
import time;
start = time.time();
elementA = np.random.randint(1,100,1_000_000);
elementB = np.random.randint(1,100,1_000_000);
addition = elementA + elementB;
end = time.time();
print("Time Taken by Numpy Array Addition is",end-start,"'s");

Time Taken by Numpy Array is 0.0268552303314209 's


*2.Element-wise Multiplication*

In [5]:
import numpy as np;
import time;
start = time.time();
elementA = np.random.randint(1,100,1_000_000);
elementB = np.random.randint(1,100,1_000_000);
addition = elementA * elementB;
end = time.time();
print("Time Taken by Numpy Array Multiplication is",end-start,"'s");

Time Taken by Numpy Array Multiplication is 0.02645730972290039 's


*3. Dot Product*

In [7]:
import numpy as np;
import time;
start = time.time();
elementA = np.random.randint(1,100,1_000_000);
elementB = np.random.randint(1,100,1_000_000);
addition = np.dot(elementA,elementB);
end = time.time();
print("Time Taken by Numpy Dot Product is",end-start,"'s");

Time Taken by Numpy Dot Product is 0.02536320686340332 's


4.Matrix Multiplication

In [9]:
import numpy as np;
import time;
start = time.time();
elementA = np.random.randint(1,100,(1000,1000));
elementB = np.random.randint(1,100,(1000,1000));
addition = np.dot(elementA,elementB);
end = time.time();
print("Time Taken by Numpy Matrix Multiplication is",end-start,"'s");

Time Taken by Numpy Matrix Multiplication is 3.115245819091797 's
